B2B\BlogBundle\Entity\PostMeta:
    type: entity
    table: post_meta
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        attributeid:
            type: smallint
            nullable: false
            options:
                unsigned: false
            column: attributeId
        postid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: postId
        value:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
